version: '3.8'

services:
    pgdb:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=Crm
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
