# Generated by Django 4.2.3 on 2023-07-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='paid', max_length=255),
            preserve_default=False,
        ),
    ]
